/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainView.java
 *
 * Created on Jan 17, 2012, 9:28:28 AM
 */
package Views;

import Controllers.UploadController;
import Models.UploadModel;
import java.awt.BorderLayout;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileFilter;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

/**
 *
 * @author afannin1
 */
public class MainView extends javax.swing.JPanel {
    File path;
    public String[] inputArr = new String[4]; //Number of checkboxes.  Change this later
    /** Creates new form MainView */
    public MainView() {
        initComponents();
    }

    private File getFilePath() {
        JFileChooser chooser = new JFileChooser();
        FileFilter filter;
        chooser.setDialogTitle("Open File");
        int returnVal = chooser.showOpenDialog(this); 
        
        if (returnVal == JFileChooser.APPROVE_OPTION)
            return chooser.getSelectedFile();
        else if (returnVal == JFileChooser.CANCEL_OPTION)           //NULLREFERENCEEXCEPTION  FIX THIS!
            return null;
        else
            return null;
    }
     
    public void setActionListeners(ActionListener al) {
        uploadButton.setActionCommand("upload");
        uploadButton.addActionListener(al);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        uploadButton = new javax.swing.JButton();
        intervalTextField = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        intervalLabel = new javax.swing.JLabel();
        lineLabel = new javax.swing.JLabel();
        lineTextField = new javax.swing.JTextField();
        apiLabel = new javax.swing.JLabel();
        projectLabel = new javax.swing.JLabel();
        templateLabel = new javax.swing.JLabel();
        templateTextField = new javax.swing.JTextField();
        projectTextField = new javax.swing.JTextField();
        apiTextField = new javax.swing.JTextField();
        fileLabel = new javax.swing.JLabel();

        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        uploadButton.setText("Upload");

        intervalTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                intervalTextFieldFocusLost(evt);
            }
        });

        intervalLabel.setText("Upload Interval:");

        lineLabel.setText("Start Line:");

        lineTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lineTextFieldFocusLost(evt);
            }
        });

        apiLabel.setText("API Key:");

        projectLabel.setText("Project Key:");

        templateLabel.setText("Template ID:");

        templateTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                templateTextFieldFocusLost(evt);
            }
        });

        projectTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                projectTextFieldFocusLost(evt);
            }
        });

        apiTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                apiTextFieldFocusLost(evt);
            }
        });

        fileLabel.setText("File Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(templateLabel)
                    .addComponent(apiLabel)
                    .addComponent(projectLabel)
                    .addComponent(lineLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(templateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(lineTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(apiTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(intervalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(intervalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fileLabel)
                        .addGap(18, 18, 18)
                        .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(browseButton))
                    .addComponent(uploadButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileLabel)
                    .addComponent(browseButton))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apiLabel)
                    .addComponent(apiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectLabel)
                    .addComponent(projectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(templateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(templateLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lineLabel)
                    .addComponent(lineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intervalLabel)
                    .addComponent(intervalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(uploadButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        File filePath;
        filePath = this.getFilePath();
        if (filePath != null)
            this.path = filePath;
        pathTextField.setText(path.toString());
    }//GEN-LAST:event_browseButtonActionPerformed

    private void intervalTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_intervalTextFieldFocusLost
        //inputArr[0] = intervalTextField.getText();
    }//GEN-LAST:event_intervalTextFieldFocusLost

    private void lineTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lineTextFieldFocusLost
        inputArr[3] = lineTextField.getText();
    }//GEN-LAST:event_lineTextFieldFocusLost

    private void templateTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_templateTextFieldFocusLost
        inputArr[2] = templateTextField.getText();
    }//GEN-LAST:event_templateTextFieldFocusLost

    private void projectTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_projectTextFieldFocusLost
        inputArr[1] = projectTextField.getText();
    }//GEN-LAST:event_projectTextFieldFocusLost

    private void apiTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apiTextFieldFocusLost
        inputArr[0] = apiTextField.getText();
    }//GEN-LAST:event_apiTextFieldFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apiLabel;
    private javax.swing.JTextField apiTextField;
    private javax.swing.JButton browseButton;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JLabel intervalLabel;
    private javax.swing.JFormattedTextField intervalTextField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lineLabel;
    private javax.swing.JTextField lineTextField;
    private javax.swing.JTextField pathTextField;
    private javax.swing.JLabel projectLabel;
    private javax.swing.JTextField projectTextField;
    private javax.swing.JLabel templateLabel;
    private javax.swing.JTextField templateTextField;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables
}
