/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SettingsView.java
 *
 * Created on Jan 17, 2012, 9:50:17 AM
 */
package Views;

import Controllers.UploadController;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author afannin1
 */
public class SettingsView extends javax.swing.JPanel {
    public String timeInterval;
    /** Creates new form SettingsView */
    public SettingsView() {
        initComponents();
        
        //intervalTextField.setValue();
    }
    
    public void setActionListeners(ActionListener al) {
        intervalButton.setActionCommand("interval");
        intervalButton.addActionListener(al);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intervalButton = new javax.swing.JButton();
        intervalTextField = new javax.swing.JFormattedTextField();

        intervalButton.setText("Set Upload Interval");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(intervalTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(intervalButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intervalButton)
                    .addComponent(intervalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(266, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton intervalButton;
    public javax.swing.JFormattedTextField intervalTextField;
    // End of variables declaration//GEN-END:variables
}
